# ===========================
# SERVER
# ===========================
server.port=${SERVER_PORT:8081}

# ===========================
# DATABASE
# ===========================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/kodhandarama_sangam_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Mani@26092003}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

# ===========================
# EMAIL (Gmail SMTP)
# ===========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME:srikodandaramasangamu@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:itmmyrznadscojwn}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# ===========================
# APP
# ===========================
spring.application.name=kodhandarama-sangam
